//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _232cf3cfc0a4672e9441a6595e306408_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("232cf3cfc0a4672e9441a6595e306408-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _232cf3cfc0a4672e9441a6595e306408_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("232cf3cfc0a4672e9441a6595e306408-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _428763b1a4cd7205035a189fb9e96fd9_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("428763b1a4cd7205035a189fb9e96fd9-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8683e0e261dc7c075c318a75bbd34bf3_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("8683e0e261dc7c075c318a75bbd34bf3-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8683e0e261dc7c075c318a75bbd34bf3_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("8683e0e261dc7c075c318a75bbd34bf3-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8683e0e261dc7c075c318a75bbd34bf3_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("8683e0e261dc7c075c318a75bbd34bf3-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _f9fbf6__1__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_f9fbf6__1_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bill_Icon_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Bill_Icon-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black_and_White_Illustrative_Pet_Shop_Logo {
            get {
                object obj = ResourceManager.GetObject("Black and White Illustrative Pet Shop Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black_and_White_Illustrative_Pet_Shop_Logo__1_ {
            get {
                object obj = ResourceManager.GetObject("Black and White Illustrative Pet Shop Logo (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ccf6c9a2b7db62ca1405fd73e4c36a36_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("ccf6c9a2b7db62ca1405fd73e4c36a36-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ccf6c9a2b7db62ca1405fd73e4c36a36_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("ccf6c9a2b7db62ca1405fd73e4c36a36-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ccf6c9a2b7db62ca1405fd73e4c36a36_removebg_preview2 {
            get {
                object obj = ResourceManager.GetObject("ccf6c9a2b7db62ca1405fd73e4c36a36-removebg-preview2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_5__2025__10_26_11_PM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 5, 2025, 10_26_11 PM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_8__2025__04_13_28_PM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 8, 2025, 04_13_28 PM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_8__2025__04_13_28_PM1 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 8, 2025, 04_13_28 PM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_8__2025__04_13_28_PM2 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 8, 2025, 04_13_28 PM2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_8__2025__04_22_37_PM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 8, 2025, 04_22_37 PM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_8__2025__04_22_37_PM1 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 8, 2025, 04_22_37 PM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_8__2025__04_26_35_PM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 8, 2025, 04_26_35 PM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_8__2025__04_26_35_PM1 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 8, 2025, 04_26_35 PM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_8__2025__04_28_14_PM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 8, 2025, 04_28_14 PM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_8__2025__04_28_14_PM1 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 8, 2025, 04_28_14 PM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_8__2025__04_28_14_PM2 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 8, 2025, 04_28_14 PM2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_8__2025__04_28_14_PM3 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 8, 2025, 04_28_14 PM3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_9__2025__03_15_45_AM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 9, 2025, 03_15_45 AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_9__2025__03_19_44_AM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 9, 2025, 03_19_44 AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_9__2025__03_19_44_AM1 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 9, 2025, 03_19_44 AM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_9__2025__03_39_26_AM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 9, 2025, 03_39_26 AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_9__2025__03_47_34_AM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 9, 2025, 03_47_34 AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_9__2025__05_22_18_AM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 9, 2025, 05_22_18 AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_9__2025__05_24_41_AM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 9, 2025, 05_24_41 AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_9__2025__05_39_00_AM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 9, 2025, 05_39_00 AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_Jun_9__2025__05_39_00_AM1 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image Jun 9, 2025, 05_39_00 AM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_May_11__2025__11_44_58_PM {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image May 11, 2025, 11_44_58 PM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_May_11__2025__11_44_58_PM1 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image May 11, 2025, 11_44_58 PM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_May_11__2025__11_44_58_PM2 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image May 11, 2025, 11_44_58 PM2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cute_gray_cat_waving_paw_cartoon_vector_illustration___Premium_Vector_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("Cute_gray_cat_waving_paw_cartoon_vector_illustration___Premium_Vector-removebg-pr" +
                        "eview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__1__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("download__1_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__2__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("download__2_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("download-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap freepik_br_ab5157e8_6f06_43e7_9ce1_114c8ed17b94 {
            get {
                object obj = ResourceManager.GetObject("freepik_br_ab5157e8-6f06-43e7-9ce1-114c8ed17b94", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lindo_labrador_retriever_cachorro_dibujos_animados_vector_ilustración___Vector_Premium__1__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Lindo_labrador_retriever_cachorro_dibujos_animados_vector_ilustración___Vector_Pr" +
                        "emium__1_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Set_of_animals_character_vector_illustrations___Premium_AI_generated_vector_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Set_of_animals_character_vector_illustrations___Premium_AI-generated_vector-remov" +
                        "ebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Worker_free_icons_designed_by_nawicon_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Worker_free_icons_designed_by_nawicon-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yellow_Fish_Clipart_Transparent_Background__Yellow_Cartoon_Fish_Clipart__Fish_Clipart__Cartoon_Clipart__Clipart_PNG_Image_For_Free_Download_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Yellow_Fish_Clipart_Transparent_Background__Yellow_Cartoon_Fish_Clipart__Fish_Cli" +
                        "part__Cartoon_Clipart__Clipart_PNG_Image_For_Free_Download-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap 金魚のイラスト_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("金魚のイラスト-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
